version: 2.1

executors:
  docker-small:
    docker:
      - image: cimg/base:current
    resource_class: small

commands:
  fail-steps:
    steps:
      - run: echo "this will be failed intentionally"
      - run: exit 1

jobs:
  success-job:
    type: no-op
    
  failed-job1:
    executor: docker-small
    steps:
      - fail-steps

  failed-job2:
    executor: docker-small
    steps:
      - fail-steps

  failed-job3:
    executor: docker-small
    steps:
      - fail-steps

workflows:
  failed-test:
   jobs:
     - failed-job1
     - failed-job2
     - failed-job3
     - success-job:
          requires:
            - failed-job2:
                  - failed
            - failed-job2:
                  - failed
            - failed-job2:
                  - failed
