version: 2.1

executors:
  docker-small:
    docker:
      - image: cimg/base:current
    resource_class: small

commands:
  default-steps:
    steps:
      - run: echo "this will be failed intentionally"
      - run: exit 0

jobs:
  connector:
    type: no-op

  test:
    executor: docker-small
    parameters:
      build:
        type: string
        default: "docker"
      version:
        type: integer
        default: 1
    steps:
      - run: echo <<parameters.version>>
      - run: echo <<parameters.build>>
      - default-steps

  report:
    executor: docker-small
    steps:
      - default-steps

workflows:
  test-and-report:
    jobs:
      - test:
          matrix:
            parameters:
              build: [ docker ]
              version: [ 1, 2, 3 ]

      - report:
          requires:
            - test:
              - success
              - failed
              - canceled
